experiments:
  - None

Model:
  random_forrest:
    type: RandomForestClassifier
    params:
      n_estimators: 100
      max_depth: 10
      random_state: 42
  
  gradient_boosting:
    type: GradientBoostingClassifier
    params:
      n_estimators: 100
      learning_rate: 0.1
      max_depth: 3
      random_state: 42