# Ran the command to select different models for experiments
# dvc exp run -S experiments.Model=random_forest
# dvc exp run -S experimen
experiments:
  Model: random_forest     # default model experiment

Model:
  random_forest:
    type: RandomForestClassifier
    params:
      n_estimators: 100
      max_depth: 10
      random_state: 42

  gradient_boosting:
    type: GradientBoostingClassifier
    params:
      n_estimators: 100
      learning_rate: 0.1
      max_depth: 3
      random_state: 42

data:
  test_size: 0.2
  random_state: 42
